WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0323+0018
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0328-0710
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0400-0652
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0752+2019
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0813+0905
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0820+1801
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0821+1450
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0859+1001
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1345+1228
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1402+1540
Traceback (most recent call last):
  File "/home/insepien/dualAGN/cutouts/make_cutout.py", line 43, in <module>
    exp_path = glob.glob(os.path.expanduser("~/raw-data-agn/mos-fits-agn/2020-02-22_J_"+args.objectName+"*.mos.fits"))[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1504+0151
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1516+0529
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0323+0018
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0328-0710
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0400-0652
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0752+2019
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0813+0905
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0820+1801
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0821+1450
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0859+1001
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0901+1815
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0906+1840
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0912+0148
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0918+1100
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0918+1207
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0918+1406
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0926+0724
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0932+1611
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0944+1649
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1000+1242
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1015-0017
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1030+0425
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1044+0637
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1052+0054
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1115+1542
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1128+0500
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1138+0342
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1140+0918
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1144+1111
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1204+0335
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1215+1344
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1222-0007
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1245+0535
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1308+0759
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1336+0803
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1338+0803
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1340-0308
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1341-0049
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1345+1228
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1402+0215
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1402+1540
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1425-0058
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1504+0151
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1516+0529
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0323+0018
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0328-0710
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0400-0652
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0752+2019
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0813+0905
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0820+1801
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0821+1450
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0859+1001
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0901+1815
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0906+1840
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0912+0148
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0918+1100
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0918+1207
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0918+1406
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0926+0724
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0932+1611
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J0944+1649
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1000+1242
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1015-0017
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1030+0425
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1044+0637
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1052+0054
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1115+1542
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1128+0500
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1138+0342
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1140+0918
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1144+1111
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1204+0335
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1215+1344
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1222-0007
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1245+0535
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1308+0759
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1336+0803
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1338+0803
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1340-0308
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1341-0049
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1345+1228
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1402+0215
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1402+1540
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1425-0058
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1504+0151
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter values: MJD-OBS and DATE-OBS are inconsistent'. [astropy.wcs.wcs]
Finished J1516+0529
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '120.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '176.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '75.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '145.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '160.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '193.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '109.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '99.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '156.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '109.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '82.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '68.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '132.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '109.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '212.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '160.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '213.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '120.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '132.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '109.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '176.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '99.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '120.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '120.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '60.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '240.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '109.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '193.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '132.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '160.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '132.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '132.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '176.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '90.,'
usage: make_cutout.py [-h] [--outDir OUTDIR] [--cutSize CUTSIZE]
                      [--objectName OBJECTNAME] [--makeMulti]
make_cutout.py: error: argument --cutSize: invalid int value: '99.'
